default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: equidist_development

test:
  <<: *default
  database: equidist_test

production:
  url: <%= ENV["DATABASE_URL"] %>